name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull dossmk27/new-sample-ci-cd:latest
    - name: Delete Old docker container
      run: sudo docker rm -f new-sample-ci-cd-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name new-sample-ci-cd-container dossmk27/new-sample-ci-cd
